#!/bin/bash
cd /home/zhangqiang/Hexo
rm -rf /home/zhangqiang/Hexo/themes/next/.git
#git初始化
git init
#创建hexo分支，用来存放源码
git checkout -b hexo
#git 文件添加
git add .
#git 提交
echo "请输入commit："
read A
git commit -m "init"
#添加远程仓库
git remote add origin git@github.com:21CDS/21CDS.github.io.git
#push到hexo分支
git push origin hexo
